# Generated by Django 3.1.3 on 2020-11-08 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='skype_link',
            new_name='skype_username',
        ),
    ]
