# Generated by Django 3.1.3 on 2020-11-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('community', '0003_auto_20201108_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='members',
            field=models.ManyToManyField(related_name='programs', to='community.Profile'),
        ),
    ]
