# Generated by Django 3.1.3 on 2020-11-08 08:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0004_auto_20201108_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='members',
            field=models.ManyToManyField(related_name='programs', to=settings.AUTH_USER_MODEL),
        ),
    ]
